version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - url-shorten-network
  backend:
    restart: always
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - url-shorten-network
  mongodb:
    restart: always
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - url-shorten-network

volumes:
  dbdata:

networks:
  url-shorten-network:
    driver: bridge
